#!/bin/bash

cd ~/Documents

curl https://pypi.python.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz > virtualenv-15.1.0.tar.gz

tar -zxvf virtualenv-15.1.0.tar.gz && rm virtualenv-15.1.0.tar.gz

python virtualenv-15.1.0/virtualenv.py -p python3 env
source env/bin/activate

pip3 install numpy
pip3 install scipy
pip3 install matplotlib
pip3 install scikit-learn
pip3 install pandas
pip3 install sympy
pip3 install jupyter

