#!/bin/bash

cd ~/Documents

pip3 install --user virtualenv
python3 -m virtualenv env
source env/bin/activate

pip3 install numpy
pip3 install scipy
pip3 install matplotlib
pip3 install scikit-learn
pip3 install pandas
pip3 install sympy
pip3 install jupyter

