#!/bin/bash

cd ~/Documents

curl  https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.1.0.tar.gz > virtualenv-15.1.0.tar.gz

tar -zxvf virtualenv-15.1.0.tar.gz

mv virtualenv-15.1.0/virtualenv.py ~/Documents

python3 virtualenv.py -p python3 env
source env/bin/activate

pip3 install numpy
pip3 install scipy
pip3 install matplotlib
pip3 install scikit-learn
pip3 install pandas
pip3 install sympy
pip3 install jupyter

